-- MySQL Script generated by MySQL Workbench
-- Tue May  5 14:18:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Playbil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Playbil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Playbil` DEFAULT CHARACTER SET utf8 ;
USE `Playbil` ;

-- -----------------------------------------------------
-- Table `Playbil`.`Worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Playbil`.`Worker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Playbil`.`Theater`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Playbil`.`Theater` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Playbil`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Playbil`.`Type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Playbil`.`Theatrical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Playbil`.`Theatrical` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT(1) NULL,
  `time` DATETIME NULL,
  `duration_min` INT NULL,
  `Theater_id` INT NOT NULL,
  `tickets_url` VARCHAR(255) NULL,
  `Type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Theater_id`, `Type_id`),
  INDEX `fk_Theatrical_Theater1_idx` (`Theater_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Theatrical_Type1_idx` (`Type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Theatrical_Theater1`
    FOREIGN KEY (`Theater_id`)
    REFERENCES `Playbil`.`Theater` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Theatrical_Type1`
    FOREIGN KEY (`Type_id`)
    REFERENCES `Playbil`.`Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Playbil`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Playbil`.`Genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Playbil`.`Artist_has_Theatrical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Playbil`.`Artist_has_Theatrical` (
  `Worker_id` INT NOT NULL,
  `Theatrical_id` INT NOT NULL,
  `theatrical_role` VARCHAR(128) NULL,
  PRIMARY KEY (`Worker_id`, `Theatrical_id`),
  INDEX `fk_Artist_has_Theatrical_Theatrical1_idx` (`Theatrical_id` ASC) VISIBLE,
  INDEX `fk_Artist_has_Theatrical_Artist1_idx` (`Worker_id` ASC) VISIBLE,
  CONSTRAINT `fk_Artist_has_Theatrical_Artist1`
    FOREIGN KEY (`Worker_id`)
    REFERENCES `Playbil`.`Worker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artist_has_Theatrical_Theatrical1`
    FOREIGN KEY (`Theatrical_id`)
    REFERENCES `Playbil`.`Theatrical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Playbil`.`Theatrical_has_Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Playbil`.`Theatrical_has_Genre` (
  `Theatrical_id` INT NOT NULL,
  `Genre_id` INT NOT NULL,
  PRIMARY KEY (`Theatrical_id`, `Genre_id`),
  INDEX `fk_Theatrical_has_Genre_Genre1_idx` (`Genre_id` ASC) VISIBLE,
  INDEX `fk_Theatrical_has_Genre_Theatrical1_idx` (`Theatrical_id` ASC) VISIBLE,
  CONSTRAINT `fk_Theatrical_has_Genre_Theatrical1`
    FOREIGN KEY (`Theatrical_id`)
    REFERENCES `Playbil`.`Theatrical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Theatrical_has_Genre_Genre1`
    FOREIGN KEY (`Genre_id`)
    REFERENCES `Playbil`.`Genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
